services:
  mariadb:
    image: mariadb
    pull_policy: never
    restart: unless-stopped
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    container_name: mariadb_container
    env_file: .env
    secrets:
      - database_root_password
      - database_user_password
    networks:
      - wp_net
    volumes:
      - db-data:${WP_DATABASE_PATH}

  wordpress:
    image: wordpress
    pull_policy: never
    restart: unless-stopped
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    container_name: wordpress_container
    env_file: .env
    secrets: 
      - database_user_password
      - wp_admin_password
    volumes:
      - html:${WP_FILE_PATH}
    networks:
      - wp_net
    depends_on:
      - mariadb

  nginx:
    image: nginx
    pull_policy: never
    restart: unless-stopped
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx_container
    env_file: .env
    secrets:
      - nginx_ssl_crt
      - nginx_ssl_key
      - nginx_ssl_csr
    ports:
      - "443:443"
    volumes:
      - html:${WP_FILE_PATH}
    networks:
      - wp_net
    depends_on:
      - wordpress

networks:
  wp_net:
    name: wp_net

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/db-data # must be the absolute host path and already exist
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/html # must be the absolute host path and already exist

secrets:
  database_root_password:
    file: ${SECRET_PATH}/database_root_password.txt
  database_user_password:
    file: ${SECRET_PATH}/database_user_password.txt
  wp_admin_password:
    file: ${SECRET_PATH}/wp_admin_password.txt
  nginx_ssl_key:
    file: ${SECRET_PATH}/server.key
  nginx_ssl_crt:
    file: ${SECRET_PATH}/server.crt
  nginx_ssl_csr:
    file: ${SECRET_PATH}/server.csr
