services:
  mariadb:
    pull_policy: never
    build:
      context: ./mariadb/
      dockerfile: Dockerfile
    container_name: mariadb_container
    # ports:
    #   - "3306:3306" # when to investigate from host
    networks:
      - wp_net
    volumes:
      - db-data:/var/lib/mysql/

  wordpress:
    pull_policy: never
    build:
      context: ./wordpress/
      dockerfile: Dockerfile
    container_name: wordpress_container
    networks:
      - wp_net
    depends_on:
      - mariadb

  nginx:
    pull_policy: never
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: nginx_container
    ports:
      - "8080:8080"
    volumes:
      - html:/var/www/html
    networks:
      - wp_net
    depends_on:
      - wordpress

networks:
  wp_net:
    name: wp_net

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/ymizuniw/Desktop/Inception2/db-data # must be the absolute host path and already exist
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/ymizuniw/Desktop/Inception2/html # must be the absolute host path and already exist
