worker_processes 2;

error_log /var/log/nginx-error.log info;

events {
    worker_connections 2048;
}

http {

    include mime.types;
    default_type aplication/octet-stream;

    upstream wp_fastcgi_passes {
        server wordpress:9000;
    }

    server {
        listen 8080;

        root /var/www/html/;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
            fastcgi_pass wp_fastcgi_passes;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
